In [1]:
import numpy as np

In [2]:
print(np.__version__)
np.show_config()

1.14.2
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/kazukimasumura/.pyenv/versions/anaconda3-5.0.1/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/kazukimasumura/.pyenv/versions/anaconda3-5.0.1/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/kazukimasumura/.pyenv/versions/anaconda3-5.0.1/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/kazukimasumura/.pyenv/versions/anaconda3-5.0.1/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/kazukimasumura/.pyenv/versions/anaconda3-5.0.1/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/kazukimasumura/.pyenv/versions/anaconda3-5.0.1/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/kazukimasumura/.pyenv/versions/anaconda3-5.0.1/lib']
    def

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
Z = np.zeros((10,10))
print("{0:d} bytes".format(Z.size * Z.itemsize))

# 要素数
print(Z.size)

# 一要素の占めるメモリサイズ
print(Z.itemsize)

800 bytes
100
8


In [7]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
Z = np.arange(10, 50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [11]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
# 要素が0でないインデックス番号を配列にする
nz = np.nonzero([1,2,4,0,0,5])
print(nz)

(array([0, 1, 2, 5]),)


In [16]:
Z = np.random.random((3, 3, 3))
print(Z)

[[[0.57043447 0.82145228 0.03157218]
  [0.67325118 0.25190594 0.69664969]
  [0.11027266 0.51551771 0.96187063]]

 [[0.42672915 0.34132477 0.93819076]
  [0.96415777 0.14301259 0.51747911]
  [0.92993053 0.03104934 0.82910862]]

 [[0.53709727 0.74670291 0.20262648]
  [0.35869149 0.77266716 0.42871519]
  [0.87723571 0.19947533 0.05545975]]]


In [17]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0009231231137873941 0.9834936095161672


In [18]:
Z = np.random.random(10)
m = Z.mean()
print(m)

0.37831397608270056


In [22]:
Z = np.ones((10, 10))
# 行番号、列番号同時に満たすもののみ変更される
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [23]:
Z = np.ones((5,5))
# 行列の前後に文字を詰めるメソッド（padding）
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [26]:
# なぜだ。。。
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [33]:
Z = np.diag(1 + np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]]


In [34]:
Z = np.zeros((8, 8), dtype=int)
# ::はstop の省略
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [35]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)
